// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWt8w8y2xeRFXbgtZBZ_Ox3gdsvZhYOm0',
    appId: '1:589816305171:web:ac756cb432e7907f3b91e6',
    messagingSenderId: '589816305171',
    projectId: 'campagna-di-davide',
    authDomain: 'campagna-di-davide.firebaseapp.com',
    storageBucket: 'campagna-di-davide.firebasestorage.app',
    measurementId: 'G-79JFDCEZM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVK0LQ9vWnlRO14pqrhV4QMlpB1z7XEIo',
    appId: '1:589816305171:android:810ae9c7fff2b3ad3b91e6',
    messagingSenderId: '589816305171',
    projectId: 'campagna-di-davide',
    storageBucket: 'campagna-di-davide.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcBNfDrzr5K5iiwppqkNXIgovOHMvbSBg',
    appId: '1:589816305171:ios:42dbe3f8ee237fc73b91e6',
    messagingSenderId: '589816305171',
    projectId: 'campagna-di-davide',
    storageBucket: 'campagna-di-davide.firebasestorage.app',
    iosBundleId: 'com.example.campagnaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcBNfDrzr5K5iiwppqkNXIgovOHMvbSBg',
    appId: '1:589816305171:ios:42dbe3f8ee237fc73b91e6',
    messagingSenderId: '589816305171',
    projectId: 'campagna-di-davide',
    storageBucket: 'campagna-di-davide.firebasestorage.app',
    iosBundleId: 'com.example.campagnaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWt8w8y2xeRFXbgtZBZ_Ox3gdsvZhYOm0',
    appId: '1:589816305171:web:cf5654b7c553e9953b91e6',
    messagingSenderId: '589816305171',
    projectId: 'campagna-di-davide',
    authDomain: 'campagna-di-davide.firebaseapp.com',
    storageBucket: 'campagna-di-davide.firebasestorage.app',
    measurementId: 'G-9L7CGECB06',
  );
}
